### ISSUE TITLE
Server doesnt start

### ISSUE THREAD

**Issue by nemoo** [klaemo/react-es6#1]
Hi!

When i run it via 'npm start', it gets to the point where it prints this: 

> react-es6@1.0.0 watch F:\temp\react-es6-master
> watchify index.js -d -t babelify -o public/bundle.js

and then it stops.

Any idea on how i could debug this?

**Comment by klaemo** [comment]
Oh, apparently the `&` bash operator doesn't work on windows :( I'll look around to see what we can do about this.
You can manually do `npm run watch` and `node server.js` in different terminal windows.

**Comment by klaemo** [comment]
The problem is `cmd.exe` (which I assume you're using). I don't know what windows people use in gerneral but there are:
- https://cygwin.com/ or
- http://win-bash.sourceforge.net/

which provider a better command line.

**Comment by nemoo** [comment]
Thanks a lot, that was the problem.
